S03 us25
WildCodeSchool/orleans-0919-php-carni-and-co pull request #103
Opened 2019-12-17 16:04 UTC by V4lou

2019-12-17 16:25 UTC, Tenkho approved these changes

2019-12-18 09:09 UTC, sblondeau requested changes

2019-12-18 09:09 UTC, sblondeau commented on src/Entity/Nutrient.php
> +     *     min = 1,
le min à un ne sert à rien car tu as dejà un NotBlank qui s'assure que le titre n'est pas vide (il faudrait que tu mettes le message d'erreur sur le notBlank plutot
par contre il te manque une verif de Length max à 80 !

2019-12-18 09:09 UTC, sblondeau commented on src/Entity/Nutrient.php
> +     *     min = 1,
inutile le min à enlever (pas de max à faire là vu que c'est un text)

2019-12-18 15:45 UTC, sblondeau approved these changes

2020-01-02 13:28 UTC, merged