display editProduct
WildCodeSchool/orleans-0919-php-carni-and-co pull request #111
Opened 2019-12-18 09:59 UTC by Oxy-Romain

2019-12-18 10:08 UTC, Tenkho approved these changes

2019-12-18 15:46 UTC, sblondeau approved these changes

2019-12-18 15:46 UTC, sblondeau requested changes

2019-12-18 15:46 UTC, sblondeau commented on templates/product/edit.html.twig
>  {% block title %}Edit Product{% endblock %}
traduction manquante

2020-01-01 18:00 UTC, sblondeau approved these changes

2020-01-01 18:01 UTC, merged