S03 us10 form add animal
WildCodeSchool/orleans-0919-php-carni-and-co pull request #120
Opened 2020-01-02 13:37 UTC by Olivier-Jamet

2020-01-06 08:40 UTC, Oxy-Romain requested changes

2020-01-06 08:40 UTC, Oxy-Romain commented on templates/admin/navbarAdmin.html.twig
> +                <a class="nav-link-admin" href="{{ path('animal_index') }}">Homepage</a>
Il faut mettre le Texte en francais, meme pour un nom commun comme celui la

2020-01-06 08:40 UTC, Oxy-Romain commented on templates/animal/show.html.twig
> +                     alt="picture of {{ animal.name }}">
le 'alt' aussi est en francais

2020-01-06 11:26 UTC, sblondeau requested changes
ta US est sur le add du CRUD, on doit pas avoir d'autres fichier modifiés, or ici j'ai du edit et delete aussi

2020-01-06 11:26 UTC, sblondeau commented on templates/animal/_delete_form.html.twig
>  <form method="post" action="{{ path('animal_delete', {'id': animal.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
ta PR est sur l'add, je ne devrais pas avoir ce fichier de modifié. En plus tu modifie le bouton mais pas le onsubmit...

2020-01-06 11:26 UTC, sblondeau commented on templates/animal/edit.html.twig
> +    <h1 class="animalTitle">Modifier un Animal</h1>
idem ici je ne dois pas avoir cette partie modifié, ça sera pour la US de l'edit

2020-01-07 10:18 UTC, Oxy-Romain approved these changes

2020-01-07 13:06 UTC, sblondeau approved these changes

2020-01-07 13:06 UTC, merged