update entityPorduct
WildCodeSchool/orleans-0919-php-carni-and-co pull request #124
Opened 2020-01-02 16:37 UTC by Oxy-Romain

2020-01-02 20:53 UTC, Tenkho approved these changes

2020-01-03 11:35 UTC, sblondeau requested changes

2020-01-03 11:35 UTC, sblondeau commented on src/Entity/Product.php
> +    /**
manque pas mal d'@assert sur ce fichier
(bar code length, assert\Type boolean sur tous les booleens, etc.)

2020-01-07 15:16 UTC, sblondeau approved these changes

2020-01-07 15:16 UTC, merged