Us36 s04 -> Add.
WildCodeSchool/orleans-0919-php-carni-and-co pull request #164
Opened 2020-01-07 15:47 UTC by Mikami45

Ajout du Crud de "Bring" + modification de ce qui concerne le "add".

2020-01-07 17:01 UTC, Oxy-Romain approved these changes

2020-01-07 22:10 UTC, sblondeau requested changes

2020-01-07 22:10 UTC, sblondeau commented on src/Controller/BringController.php
> +use App\Entity\Bring;
il semblerait que ce soit plutot "Intake" le bon terme, mais ça vaut peut etre plus le coup de tout modifier maintenant...

2020-01-07 22:10 UTC, sblondeau commented on src/Controller/BringController.php
> +
manque le flash message

2020-01-07 22:10 UTC, sblondeau commented on src/Entity/Bring.php
> +    private $ratioProteinCalorie;
on a pas dit qu'on les enlevait les ratios ? ;-)

2020-01-07 22:10 UTC, sblondeau commented on src/Entity/Bring.php
> +    private $proteins;
les propriétés doivent etre au singulier, là y en a plusieurs au pluriel

2020-01-07 22:10 UTC, sblondeau commented on templates/bring/index.html.twig
> +                <td>{{ bring.ratioProteinCalorie }}</td>
et pour les rations tu peux laisser les colones mais il faut que ce soit calculé en fonction des 2 autres valeurs (attention à vérif qu'il n'y ait pas de division par zéro)

2020-01-08 13:54 UTC, sblondeau requested changes

2020-01-08 13:54 UTC, sblondeau commented on templates/bring/show.html.twig
> +                <td>{{ (bring.protein  /  bring.calorie * 10)|round }}</td>
il me faut un if aussi pour vérifier que le dénominateur soit != 0 (pour ici et plus bas aussi)

2020-01-08 15:44 UTC, Oxy-Romain approved these changes

2020-01-08 16:33 UTC, sblondeau approved these changes

2020-01-08 16:33 UTC, merged