S04 us18 inscription user
WildCodeSchool/orleans-0919-php-carni-and-co pull request #192
Opened 2020-01-10 03:56 UTC by Olivier-Jamet

2020-01-10 10:04 UTC, Oxy-Romain approved these changes

2020-01-10 10:04 UTC, Oxy-Romain commented on src/Form/RegistrationFormType.php
> +                        'message' => 'Please enter a password',
il faudrait que tu mettes les messages en francais

2020-01-10 10:06 UTC, Tenkho commented on src/Repository/UserRepository.php
> +        return $this->createQueryBuilder('u')
Enleve le code commenté qui sert à rien

2020-01-13 08:44 UTC, Mikami45 commented on src/Repository/UserRepository.php
> +    */
Si cela ne sert pas, à effacé

2020-01-13 08:44 UTC, Mikami45 approved these changes

2020-01-13 16:50 UTC, sblondeau requested changes

2020-01-13 16:50 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +            //$subscriber-> setEmail('email');
code commenté

2020-01-13 16:50 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +            //$admin->setEmail('email');
idem

2020-01-13 16:50 UTC, sblondeau commented on src/Entity/User.php
> +     * @ORM\Column(type="string", length=180, unique=true)
Assert length manquant

2020-01-14 10:35 UTC, Mikami45 approved these changes

2020-01-14 10:57 UTC, sblondeau approved these changes

2020-01-14 10:57 UTC, merged