S04 us18 connexion user
WildCodeSchool/orleans-0919-php-carni-and-co pull request #193
Opened 2020-01-10 05:13 UTC by Olivier-Jamet

2020-01-13 08:36 UTC, Mikami45 commented on src/Repository/UserRepository.php
> +    */
Doit être effacé !

2020-01-13 08:37 UTC, Mikami45 commented on templates/security/login.html.twig
> +    #}
Si cela ne sert pas, à effacé ausi !

2020-01-13 08:41 UTC, Mikami45 approved these changes

2020-01-13 08:42 UTC, Mikami45 commented on src/Form/RegistrationFormType.php
> +                        'message' => 'Please enter a password',
Le message doit être en français !

2020-01-13 08:43 UTC, Mikami45 approved these changes

2020-01-13 08:43 UTC, Mikami45 commented on src/Form/RegistrationFormType.php
> +                        'minMessage' => 'Your password should be at least {{ limit }} characters',
Pareil ici aussi ! En français !

2020-01-13 14:40 UTC, Mikami45 approved these changes

2020-01-14 08:42 UTC, sblondeau requested changes

2020-01-14 08:42 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +            //$subscriber-> setEmail('email');
code commenté

2020-01-14 08:42 UTC, sblondeau commented on src/DataFixtures/UserFixtures.php
> +            //$admin->setEmail('email');
idem

2020-01-14 08:42 UTC, sblondeau commented on src/Entity/User.php
> +     * @ORM\Column(type="string", length=180, unique=true)
manque l'assert length

2020-01-14 08:42 UTC, sblondeau commented on src/Form/RegistrationFormType.php
> +                        'message' => 'S\il vous plait entrez un mot de passe',
modifier le message par "Un mot de passe est requis"

2020-01-14 10:58 UTC, sblondeau requested changes

2020-01-14 10:58 UTC, sblondeau commented on src/Controller/SecurityController.php
> +        // if ($this->getUser()) {
code commenté > gateau !!!

2020-01-14 16:29 UTC, Mikami45 commented on src/Form/RegistrationFormType.php
>                          // max length allowed by Symfony for security reasons
A effacé aussi !

2020-01-14 16:30 UTC, Mikami45 approved these changes

2020-01-15 08:39 UTC, sblondeau approved these changes

2020-01-15 08:39 UTC, merged