Update product
WildCodeSchool/orleans-0919-php-carni-and-co pull request #212
Opened 2020-01-10 16:39 UTC by Oxy-Romain

2020-01-10 16:44 UTC, V4lou approved these changes

2020-01-13 08:26 UTC, sblondeau requested changes

2020-01-13 08:26 UTC, sblondeau commented on src/Entity/Ingredient.php
> +     * @ORM\ManyToMany(targetEntity="App\Entity\Product", mappedBy="ingredient")
si c'est une many to many, ça doit etre ingredient**s**

2020-01-13 08:26 UTC, sblondeau commented on src/Entity/Product.php
> +    private $ingredient;
ingredient**s**

2020-01-13 08:59 UTC, Mikami45 approved these changes

2020-01-13 10:11 UTC, sblondeau approved these changes

2020-01-13 10:11 UTC, merged