add email field in the register form
WildCodeSchool/orleans-0919-php-carni-and-co pull request #222
Opened 2020-01-15 14:16 UTC by Olivier-Jamet

2020-01-16 14:45 UTC, Mikami45 approved these changes

2020-01-16 14:50 UTC, sblondeau requested changes

2020-01-16 14:50 UTC, sblondeau commented on src/Form/RegistrationFormType.php
>              ->add('plainPassword', PasswordType::class, [
il vaudrait mieux utiliser un ReapeatedType (pour permettre de taper 2 fois le password

2020-01-17 08:34 UTC, sblondeau approved these changes

2020-01-17 08:34 UTC, merged