Css fix admin list
WildCodeSchool/orleans-0919-php-carni-and-co pull request #223
Opened 2020-01-15 15:57 UTC by Oxy-Romain

2020-01-15 16:26 UTC, Tenkho commented on templates/animal/index.html.twig
>  {% block title %}Liiste des animaux{% endblock %}
Liste s'écrit avec un seul "i".

2020-01-15 16:39 UTC, Tenkho approved these changes

2020-01-15 22:49 UTC, sblondeau requested changes

2020-01-15 22:49 UTC, sblondeau commented on templates/animal/index.html.twig
> +                <a href="{{ path('animal_edit', {'id': 'x'}) }}">
pourquoi 'x' ?

2020-01-15 22:49 UTC, sblondeau commented on templates/brand/index.html.twig
> +                        <a href="{{ path('brand_edit', {'id': 'x'}) }}"><button class="btn btn-secondary">Modifier</button></a>
idem

2020-01-15 22:49 UTC, sblondeau commented on templates/nutrient/index.html.twig
> +                        <a href="{{ path('nutrient_edit', {'id': 'x'}) }}"><button class="btn btn-secondary">Modifier</button></a>
et encore

2020-01-16 10:43 UTC, sblondeau approved these changes

2020-01-16 10:43 UTC, merged