S05 us19 admin user list
WildCodeSchool/orleans-0919-php-carni-and-co pull request #227
Opened 2020-01-16 07:03 UTC by Olivier-Jamet

2020-01-16 09:52 UTC, Mikami45 approved these changes

2020-01-16 14:49 UTC, sblondeau requested changes

2020-01-16 14:49 UTC, sblondeau commented on src/Controller/UserController.php
> +            'users' => $userRepository->findAll(),
lister les membres par ordre alphabétique

2020-01-17 08:35 UTC, sblondeau approved these changes

2020-01-17 08:35 UTC, merged