S05 us19 admin user add
WildCodeSchool/orleans-0919-php-carni-and-co pull request #249
Opened 2020-01-17 11:55 UTC by Olivier-Jamet

2020-01-18 12:34 UTC, Tenkho approved these changes

2020-01-18 19:50 UTC, sblondeau approved these changes

2020-01-18 19:52 UTC, sblondeau requested changes

2020-01-18 19:52 UTC, sblondeau commented on templates/user/new.html.twig
> +{% extends 'layout_admin.html.twig' %}
hum. L'admin n'a pas a ajouter de user non ? ni a en édter ? 
éventulellement il pourrait le delete ou les lister mais ça devrait etre tout...

2020-01-19 16:11 UTC, V4lou approved these changes

2020-01-19 19:59 UTC, sblondeau approved these changes

2020-01-19 20:00 UTC, merged