S05 us44 faq admin
WildCodeSchool/orleans-0919-php-carni-and-co pull request #259
Opened 2020-01-18 18:02 UTC by V4lou

2020-01-19 20:59 UTC, Mikami45 approved these changes

2020-01-19 20:59 UTC, Mikami45 commented on src/Repository/FaqRepository.php
> +    */
Code commenté ! A effacer ! ;D

2020-01-20 08:28 UTC, Oxy-Romain approved these changes

2020-01-20 08:50 UTC, sblondeau requested changes

2020-01-20 08:50 UTC, sblondeau commented on src/Entity/Faq.php
> +     *     min = 5,
ne met pas de limite minimum

2020-01-20 09:59 UTC, sblondeau approved these changes

2020-01-20 09:59 UTC, merged