Add Assert regex
WildCodeSchool/orleans-0919-php-carni-and-co pull request #272
Opened 2020-01-20 14:55 UTC by Olivier-Jamet

2020-01-20 20:21 UTC, Tenkho approved these changes

2020-01-20 20:53 UTC, sblondeau requested changes

2020-01-20 20:53 UTC, sblondeau commented on src/Entity/User.php
> +     * * @Assert\Regex("/^[^\W][a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\@[a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\.[a-zA-Z]{2,4}$/")
NON ! il y a un @Assert\Email qui existe déjà

2020-01-20 20:53 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Regex("/^[a-zA-Z0-9_]{3,50}$/")
pas de Regex sur le username, c'est inutile.
par contre si tu met un length 50, tu dois avoir un Assert\Length à 50 égalmeent !

2020-01-20 20:53 UTC, sblondeau commented on src/Entity/User.php
> +     * * @Assert\Regex("/^[^\W][a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\@[a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\.[a-zA-Z]{2,4}$/")
et manque le assert\length

2020-01-23 08:18 UTC, Tenkho commented on src/Entity/User.php
> +     * @Assert\Email( message = "The email '{{ value }}' is not a valid email." )
il faut mettre le message en français

2020-01-23 19:32 UTC, sblondeau requested changes

2020-01-23 19:32 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Email( message = "Cette email '{{ value }}' n'est pas valide." )
"Cet email" ou "Cette adresse email"
enlève la length min à 6 qui et inutile

2020-01-23 19:32 UTC, sblondeau requested changes

2020-01-23 19:32 UTC, sblondeau commented on src/Entity/User.php
>       *     max="80", minMessage="email invalide", maxMessage="Votre email ne doit pas contenit plus de 80 caractères")
contenir

2020-01-24 16:32 UTC, V4lou approved these changes

2020-01-24 16:48 UTC, sblondeau approved these changes

2020-01-24 16:48 UTC, merged