affichage de la note sur la page evaluation
WildCodeSchool/orleans-0919-php-carni-and-co pull request #273
Opened 2020-01-20 15:02 UTC by Tenkho

2020-01-20 15:05 UTC, V4lou approved these changes

2020-01-20 15:09 UTC, V4lou approved these changes

2020-01-20 15:50 UTC, sblondeau requested changes

2020-01-20 15:50 UTC, sblondeau commented on src/Controller/ProductController.php
> +            'note' => $note
inutile d'envoyer note en param puisque tu as un getNote. tu peux faire product.note direct dans twig !

2020-01-20 15:50 UTC, sblondeau commented on src/Entity/Product.php
> +        $calculator = new Calculator();
euh non ! le getNote doit récup la valeur en BDD, pas lancer le calcul ! ça ça doit etre fait depuis un controlleur plutot, au moment d'un add ou d'un edit, sinon à chaque getNote() tu refais tout le calcul.

2020-01-20 20:34 UTC, V4lou approved these changes

2020-01-20 20:54 UTC, sblondeau requested changes

2020-01-20 20:54 UTC, sblondeau commented on src/Controller/AdminProductController.php
> +            $calculator = new Calculator();
Calculator doit etre injecté dans les param de ta méthode, pas de "new Calculator"

2020-01-21 07:01 UTC, V4lou approved these changes

2020-01-21 08:01 UTC, sblondeau approved these changes

2020-01-21 08:02 UTC, merged