fix du filtre par note
WildCodeSchool/orleans-0919-php-carni-and-co pull request #290
Opened 2020-01-21 14:04 UTC by Tenkho

2020-01-21 14:21 UTC, V4lou approved these changes

2020-01-21 15:03 UTC, sblondeau requested changes

2020-01-21 15:03 UTC, sblondeau commented on src/Form/FilterProductType.php
> +            ->add('note', CheckboxType::class, [
c'est bizarre un checkbox... j'aurais plutot mis un select avec au choix tri par note ou par reference

2020-01-21 15:36 UTC, V4lou approved these changes

2020-01-22 09:40 UTC, sblondeau approved these changes

2020-01-22 09:40 UTC, merged