fix de tous les form delete
WildCodeSchool/orleans-0919-php-carni-and-co pull request #310
Opened 2020-01-23 15:48 UTC by Tenkho

2020-01-23 16:04 UTC, V4lou approved these changes

2020-01-23 16:06 UTC, V4lou approved these changes

2020-01-23 19:45 UTC, sblondeau requested changes

2020-01-23 19:45 UTC, sblondeau commented on src/Entity/Composition.php
> +     * @ORM\JoinColumn(onDelete="CASCADE")
vous etre sûrs de la syntaxe, car d'habitude on définit pas ça ici
c'est plutot dans la relation @ORM\ManyToOne(targetEntity=..., inversedBy=..., cascade={"remove"})

2020-01-24 13:41 UTC, V4lou approved these changes

2020-01-24 16:48 UTC, sblondeau approved these changes

2020-01-24 16:48 UTC, merged