tri par ordre alphabétique nutrition admin
WildCodeSchool/orleans-0919-php-carni-and-co pull request #313
Opened 2020-01-24 10:24 UTC by V4lou

2020-01-24 13:26 UTC, Mikami45 approved these changes

2020-01-24 16:49 UTC, sblondeau requested changes

2020-01-24 16:49 UTC, sblondeau commented on src/Controller/NutrientController.php
> +            'nutrients' => $nutrientRepository->findby(array(), array('name'=>'ASC')),
syntaxe [] et par array() pour les tableaux stp

2020-01-27 08:49 UTC, sblondeau approved these changes

2020-01-27 08:50 UTC, merged