tri par ordre alpha faq admin
WildCodeSchool/orleans-0919-php-carni-and-co pull request #314
Opened 2020-01-24 10:31 UTC by V4lou

2020-01-24 13:25 UTC, Mikami45 approved these changes

2020-01-24 16:49 UTC, sblondeau requested changes

2020-01-24 16:49 UTC, sblondeau commented on src/Controller/FaqController.php
> +            'faqs' => $faqRepository->findby(array(), array('title'=>'ASC')),
idem syntaxe [] par array()

2020-01-27 08:51 UTC, sblondeau approved these changes

2020-01-27 08:51 UTC, merged