Fix connection
WildCodeSchool/orleans-0919-php-carni-and-co pull request #319
Opened 2020-01-24 12:37 UTC by Olivier-Jamet

2020-01-24 13:28 UTC, Tenkho approved these changes

2020-01-25 12:24 UTC, sblondeau requested changes

2020-01-25 12:24 UTC, sblondeau commented on assets/scss/connexion.scss
> +    color: #000000;
couleur en variable stp

2020-01-25 12:24 UTC, sblondeau commented on templates/security/login.html.twig
> +            <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
comprends pas ce que c'est ce error.messageKey

2020-01-27 10:39 UTC, sblondeau requested changes

2020-01-27 10:39 UTC, sblondeau commented on templates/security/login.html.twig
> +            <div class="alert alert-danger">Cette identifiant n'est pas valide</div>
Cet

2020-01-28 16:32 UTC, sblondeau approved these changes

2020-01-28 16:32 UTC, merged