fix CSS/Responsive Products-Evaluation
WildCodeSchool/orleans-0919-php-carni-and-co pull request #336
Opened 2020-01-28 13:04 UTC by Oxy-Romain

2020-01-28 13:42 UTC, V4lou approved these changes

2020-01-28 16:46 UTC, sblondeau requested changes

2020-01-28 16:46 UTC, sblondeau commented on templates/user/product/show.html.twig
> +            <!--<a href="{{ path('product_pdf', {id : product.id}) }}">
code commenté

2020-01-28 17:27 UTC, V4lou approved these changes

2020-01-29 14:35 UTC, sblondeau approved these changes

2020-01-29 14:35 UTC, merged