Footer public
WildCodeSchool/orleans-0919-php-carni-and-co pull request #34
Opened 2019-12-04 14:52 UTC by V4lou

Le css et le html pour le footer

2019-12-04 16:12 UTC, Tenkho approved these changes

2019-12-04 16:43 UTC, sblondeau requested changes

2019-12-04 16:43 UTC, sblondeau commented on src/Controller/HomeController.php
>       * @Route("/home", name="home_index")
la route serait "/" plutot que "/home" non ? soit sûr que ce HomeController soit commun avec tout le monde

2019-12-04 16:46 UTC, V4lou commented on src/Controller/HomeController.php
>       * @Route("/home", name="home_index")
En fait j'ai pris la route de Romain (qui avait pushé en premier). On va voir comment changer çà.

2019-12-04 20:46 UTC, Tenkho commented on src/Controller/HomeController.php
>       * @Route("/home", name="home_index")
La route est toujours "/home", change la en seulement "/"

2019-12-05 07:52 UTC, sblondeau approved these changes

2019-12-05 07:52 UTC, merged