Navbar admin
WildCodeSchool/orleans-0919-php-carni-and-co pull request #44
Opened 2019-12-05 12:27 UTC by Mikami45

2019-12-05 13:23 UTC, V4lou approved these changes

2019-12-05 22:22 UTC, sblondeau requested changes

2019-12-05 22:22 UTC, sblondeau commented on src/Controller/AdminIndexController.php
> +            'Home_admin' => 'Administrateur',
cette variable ne sert à rien non ? à retirer

2019-12-06 09:33 UTC, V4lou approved these changes

2019-12-06 09:55 UTC, sblondeau requested changes

2019-12-06 09:55 UTC, sblondeau commented on src/Controller/AdminIndexController.php
> + * @Route ("/" , name="admin_index")
non, il faut que ta route ici soit /admin

2019-12-06 09:55 UTC, sblondeau commented on src/Controller/AdminIndexController.php
> + * @Route ("/" , name="admin_index")
et ton name juste admin

2019-12-06 09:55 UTC, sblondeau commented on src/Controller/AdminIndexController.php
> +     * @Route("/admin", name="admin_index")
et ici "/". et ton name "_index"
car en l'état là ton name est "admin_indexadmin_index"...

2019-12-06 16:32 UTC, sblondeau approved these changes

2019-12-06 16:32 UTC, merged