S01 us06
WildCodeSchool/orleans-0919-php-carni-and-co pull request #46
Opened 2019-12-05 15:03 UTC by Olivier-Jamet

Add homepage elements

2019-12-05 15:33 UTC, V4lou approved these changes

2019-12-05 22:26 UTC, sblondeau requested changes
image background trop grosse et si c'est un background, pourquoi dans un dossier uploads ? (qui lui ne devrait pas avoir son contenu versionné)
idem pour les autres images d'ailleurs

2019-12-05 22:26 UTC, sblondeau commented on templates/base.html.twig
> +<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
code à retirer (voir avec Dimitri je lui ai déjà fait faire)

2019-12-05 22:26 UTC, sblondeau commented on templates/home/index.html.twig
> +    <img src="/uploads/man_and_dog.png" class="card-img" alt="picture of a man and a dog">
l'image est administrable ou non ? 
dans tous les cas, les images sont à appelé avec {{assets("path/vers/image")}} (cf doc de webpack)

2019-12-06 09:57 UTC, V4lou approved these changes

2019-12-06 09:58 UTC, V4lou approved these changes

2019-12-06 14:55 UTC, closed without merging