ajout du carousel sur la homepage
WildCodeSchool/orleans-0919-php-carni-and-co pull request #47
Opened 2019-12-05 16:05 UTC by Tenkho

2019-12-05 16:14 UTC, V4lou approved these changes

2019-12-05 22:28 UTC, sblondeau requested changes

2019-12-05 22:28 UTC, sblondeau commented on templates/home/index.html.twig
> +                <img class="d-block w-100" src="img/img-carousel1.webp" alt="image de chien dans la nature">
les images "statiques" (non administrables) sont à mettre dans le dossier assets/images 
voir doc de webpack sur la gestion des images
dans le twig, utiliser {{assets('path/vers/image') }} pour les appeler

2019-12-06 08:43 UTC, V4lou approved these changes

2019-12-06 08:52 UTC, sblondeau approved these changes

2019-12-06 08:52 UTC, merged