mise en place de l'ajout des marques
WildCodeSchool/orleans-0919-php-carni-and-co pull request #77
Opened 2019-12-12 21:45 UTC by Tenkho

2019-12-12 21:58 UTC, Oxy-Romain approved these changes

2019-12-12 22:15 UTC, sblondeau requested changes

2019-12-12 22:15 UTC, sblondeau commented on src/Controller/MarqueController.php
> +class MarqueController extends AbstractController
c'est Brand in english... à renommer everywhere

2019-12-12 22:15 UTC, sblondeau commented on src/Entity/Marque.php
> +     * @ORM\Column(type="string", length=80)
manque les @Assert

2019-12-12 22:15 UTC, sblondeau commented on src/Entity/Marque.php
> +     * @ORM\Column(type="string", length=80)
à réfléchir, mais le nom de la marque en unique pourrait etre pertinent non ?

2019-12-12 22:15 UTC, sblondeau commented on src/Repository/MarqueRepository.php
> +    public function findByExampleField($value)
enlève le code commenté meme si généré par Sf ;-)

2019-12-13 08:49 UTC, Mikami45 approved these changes

2019-12-13 09:01 UTC, sblondeau requested changes

2019-12-13 09:01 UTC, sblondeau commented on src/Controller/BrandController.php
> +            'marques' => $brandRepository->findAll(),
brands

2019-12-13 09:01 UTC, sblondeau commented on src/Controller/BrandController.php
> +     * @Route("/", name="marque_index", methods={"GET"})
la route en français, mais le name c'est comme une variable, en english

2019-12-13 09:01 UTC, sblondeau commented on src/Controller/BrandController.php
> +     * @Route("/", name="marque_index", methods={"GET"})
je te conseille d'ajouter un name à ton annotation de Route de classe, ça t'évitera de le répéter partout

2019-12-13 09:01 UTC, sblondeau commented on templates/brand/index.html.twig
> +    <a href="{{ path('marque_new') }}"><button class="btn btn-secondary mb-3 center-button">Enregistrer une nouvelle marque</button></a>
brand partout dans le twig (sauf pour l'affichage en français bien sûr)

2019-12-13 09:01 UTC, sblondeau commented on templates/brand/show.html.twig
> +{% block title %}Marque{% endblock %}
idem dans tous les fichiers twig

2019-12-13 09:25 UTC, Oxy-Romain approved these changes

2019-12-13 09:35 UTC, sblondeau approved these changes

2019-12-13 09:35 UTC, merged