Add entity/crud // display list
WildCodeSchool/orleans-0919-php-carni-and-co pull request #79
Opened 2019-12-13 09:12 UTC by Oxy-Romain

2019-12-13 09:56 UTC, Tenkho approved these changes

2019-12-13 10:02 UTC, sblondeau requested changes

2019-12-13 10:02 UTC, sblondeau commented on src/Entity/Product.php
> +    private $bio;
$organic en anglais

2019-12-13 10:02 UTC, sblondeau commented on src/Entity/Product.php
> +     * @ORM\Column(type="blob", nullable=true)
pourquoi type=blob ?

2019-12-13 10:02 UTC, sblondeau commented on src/Migrations/Version20191212145348.php
> +<?php
PAS DE MIGRATIONS !!!!

2019-12-13 10:02 UTC, sblondeau commented on templates/product/index.html.twig
> +                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of
pas de texte en dur et en anglais ! tout devrait venir de la bdd

2019-12-16 22:31 UTC, sblondeau approved these changes

2019-12-16 22:31 UTC, merged