fix routing navbar -> admin
WildCodeSchool/orleans-0919-php-carni-and-co pull request #97
Opened 2019-12-17 09:09 UTC by Oxy-Romain

2019-12-17 09:15 UTC, Tenkho approved these changes

2019-12-17 14:50 UTC, sblondeau requested changes

2019-12-17 14:50 UTC, sblondeau commented on templates/admin/navbarAdmin.html.twig
> +            <li class="nav-item active">
ici tous vos liens sont en "active" (et en sr-only current < ça c'est pour l'accessibilité).
En fait il faut qu'il n'y ait que le lien sur lequel on se trouve actuellement qui doit etre mis en actif.
Ca demande potentiellement un peu de travail, donc vous pouvez mettre ça dans une autre US, mais au moins enlevez les active de partout

2019-12-17 15:54 UTC, Tenkho approved these changes

2019-12-17 16:35 UTC, sblondeau requested changes

2019-12-17 16:35 UTC, sblondeau commented on templates/admin/navbarAdmin.html.twig
> +                <a class="nav-link" href="#">Evaluation <span class="sr-only">(current)</span></a>
pareil pour les `<span class="sr-only">(current)</span>` !

2019-12-17 16:35 UTC, sblondeau commented on templates/admin/navbarAdmin.html.twig
> +                <a class="nav-link" href="#">Evaluation <span class="sr-only">(current)</span></a>
c'est l'equiv des activ pour les screen reader

2019-12-18 09:05 UTC, sblondeau requested changes

2019-12-18 09:05 UTC, sblondeau commented on templates/admin/navbarAdmin.html.twig
> +<nav class="navbar navbar-expand-lg navbar-light navbar-light" style="background-color: #e3d5cd">
pourquoi j'ai du style en inline ! 
https://tenor.com/view/bucher-kaamelot-gif-5295221

2019-12-18 15:41 UTC, sblondeau approved these changes

2020-01-01 18:00 UTC, merged